name: Manual Database Operations

on:
  workflow_dispatch:
    inputs:
      operation:
        description: 'Choose database operation'
        required: true
        default: 'test'
        type: choice
        options:
          - test
          - sync
          - flush

jobs:
  manual-operation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: package.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run Test
      if: ${{ github.event.inputs.operation == 'test' }}
      run: npm run test
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        NODE_ENV: production
    
    - name: Run Sync
      if: ${{ github.event.inputs.operation == 'sync' }}
      run: npm run sync
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        NODE_ENV: production
    
    - name: Run Flush
      if: ${{ github.event.inputs.operation == 'flush' }}
      run: npm run flush
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        NODE_ENV: production
    
    - name: Upload logs (if failure)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: operation-logs-${{ github.event.inputs.operation }}-${{ github.run_number }}
        path: '*.log'
        retention-days: 7