name: Weekly MF Data Rebuild

on:
  schedule:
    # Run at 1:00 AM IST (19:30 UTC previous day) on Sunday only
    - cron: '30 19 * * 6'
  push:
    # Trigger rebuild when code is pushed to main branch to ensure database stays in sync with latest changes
    branches: [ main ]
  workflow_dispatch:
    # Also allow manual triggering

jobs:
  rebuild-database:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: package.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Test Database Connection
      run: npm run test
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        NODE_ENV: production
    
    - name: Flush Database
      run: npm run flush
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        NODE_ENV: production
    
    - name: Seed Database
      run: npm run seed
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        NODE_ENV: production
    
    - name: Upload logs (if failure)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: rebuild-logs-${{ github.run_number }}
        path: '*.log'
        retention-days: 7